apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-audio-to-text-secret-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/test-audio-to-text-secret-3:37790d4757b7308e266a18666f003a8db5a75849@sha256:65763d3ed1d4d5ca3a631774e2c6b6f153a085807b24da757e899342b313e7c7 # use pre-built to bootstrap 
          name: app-inference
